In [69]:
from WindPy import *
w.start()
w.isconnected()

Welcome to use Wind Quant API for Python (WindPy)!

COPYRIGHT (C) 2021 WIND INFORMATION CO., LTD. ALL RIGHTS RESERVED.
IN NO CIRCUMSTANCE SHALL WIND BE RESPONSIBLE FOR ANY DAMAGES OR LOSSES CAUSED BY USING WIND QUANT API FOR Python.

True

In [ ]:
data = w.wsd("163406.OF", "prt_topstockholdingchanging,prt_topstockwindcode", "2020-11-01", "2022-12-05", "unit=1;order=1;Period=Q;Days=WEEKDAYS");

In [6]:
data = w.wsd("163406.OF", "prt_stockvalue,prt_topstockwindcode", "2020-11-01", "2022-12-05", "unit=1;order=1;Period=Q;Days=WEEKDAYS",usedf=True);

In [5]:
data

(0,
             PRT_STOCKVALUE PRT_TOPSTOCKWINDCODE
 2020-12-31    1.790837e+10            601318.SH
 2021-03-31    2.374960e+10            600690.SH
 2021-06-30    2.745870e+10            600690.SH
 2021-09-30    2.667316e+10            600690.SH
 2021-12-31    3.136809e+10            600690.SH
 2022-03-31    2.549094e+10            600690.SH
 2022-06-30    2.683657e+10            600690.SH
 2022-09-30    2.331552e+10            600690.SH
 2022-12-05             NaN                 None)

In [7]:
data = w.wsd("163406.OF", "prt_stockvalue,prt_topstockwindcode", "2020-11-01", "2022-12-05", "unit=1;order=2;Period=Q;Days=WEEKDAYS",usedf=True);

In [8]:
data

(0,
             PRT_STOCKVALUE PRT_TOPSTOCKWINDCODE
 2020-12-31    1.790837e+10            600690.SH
 2021-03-31    2.374960e+10            601166.SH
 2021-06-30    2.745870e+10            000001.SZ
 2021-09-30    2.667316e+10            600309.SH
 2021-12-31    3.136809e+10            600703.SH
 2022-03-31    2.549094e+10            600703.SH
 2022-06-30    2.683657e+10            600703.SH
 2022-09-30    2.331552e+10            002120.SZ
 2022-12-05             NaN                 None)

In [9]:
data = w.wsd("163406.OF", "prt_stockvalue,prt_topstockwindcode", "2020-11-01", "2022-12-05", "unit=1;order=3;Period=Q;Days=WEEKDAYS",usedf=True);

In [11]:
data

(0,
             PRT_STOCKVALUE PRT_TOPSTOCKWINDCODE
 2020-12-31    1.790837e+10            600031.SH
 2021-03-31    2.374960e+10            000001.SZ
 2021-06-30    2.745870e+10            002415.SZ
 2021-09-30    2.667316e+10            002415.SZ
 2021-12-31    3.136809e+10            600309.SH
 2022-03-31    2.549094e+10            688099.SH
 2022-06-30    2.683657e+10            600745.SH
 2022-09-30    2.331552e+10            600703.SH
 2022-12-05             NaN                 None)

In [12]:
data = w.wsd("163406.OF", "prt_stockvalue,prt_topstockwindcode", "2020-11-01", "2022-12-05", "unit=1;order=4;Period=Q;Days=WEEKDAYS",usedf=True);

In [13]:
data

(0,
             PRT_STOCKVALUE PRT_TOPSTOCKWINDCODE
 2020-12-31    1.790837e+10            000333.SZ
 2021-03-31    2.374960e+10            601318.SH
 2021-06-30    2.745870e+10            601166.SH
 2021-09-30    2.667316e+10            600703.SH
 2021-12-31    3.136809e+10            300413.SZ
 2022-03-31    2.549094e+10            000739.SZ
 2022-06-30    2.683657e+10            300413.SZ
 2022-09-30    2.331552e+10            002475.SZ
 2022-12-05             NaN                 None)

In [14]:
data = w.wsd("163406.OF", "prt_stockvalue,prt_topstockwindcode", "2020-11-01", "2022-12-05", "unit=1;order=5;Period=Q;Days=WEEKDAYS",usedf=True);

In [15]:
data

(0,
             PRT_STOCKVALUE PRT_TOPSTOCKWINDCODE
 2020-12-31    1.790837e+10            600309.SH
 2021-03-31    2.374960e+10            002415.SZ
 2021-06-30    2.745870e+10            600309.SH
 2021-09-30    2.667316e+10            601166.SH
 2021-12-31    3.136809e+10            600745.SH
 2022-03-31    2.549094e+10            300413.SZ
 2022-06-30    2.683657e+10            600754.SH
 2022-09-30    2.331552e+10            600873.SH
 2022-12-05             NaN                 None)

In [16]:
data = w.wsd("163406.OF", "prt_stockvalue,prt_topstockwindcode", "2020-11-01", "2022-12-05", "unit=1;order=6;Period=Q;Days=WEEKDAYS",usedf=True);

In [17]:
data

(0,
             PRT_STOCKVALUE PRT_TOPSTOCKWINDCODE
 2020-12-31    1.790837e+10            002594.SZ
 2021-03-31    2.374960e+10            600031.SH
 2021-06-30    2.745870e+10            600754.SH
 2021-09-30    2.667316e+10            300413.SZ
 2021-12-31    3.136809e+10            688099.SH
 2022-03-31    2.549094e+10            600745.SH
 2022-06-30    2.683657e+10            688099.SH
 2022-09-30    2.331552e+10            300413.SZ
 2022-12-05             NaN                 None)

In [18]:
data = w.wsd("163406.OF", "prt_stockvalue,prt_topstockwindcode", "2020-11-01", "2022-12-05", "unit=1;order=7;Period=Q;Days=WEEKDAYS",usedf=True);

In [19]:
data

(0,
             PRT_STOCKVALUE PRT_TOPSTOCKWINDCODE
 2020-12-31    1.790837e+10            300413.SZ
 2021-03-31    2.374960e+10            600754.SH
 2021-06-30    2.745870e+10            300413.SZ
 2021-09-30    2.667316e+10            000739.SZ
 2021-12-31    3.136809e+10            603707.SH
 2022-03-31    2.549094e+10            603707.SH
 2022-06-30    2.683657e+10            603707.SH
 2022-09-30    2.331552e+10            002938.SZ
 2022-12-05             NaN                 None)

In [20]:
data = w.wsd("163406.OF", "prt_stockvalue,prt_topstockwindcode", "2020-11-01", "2022-12-05", "unit=1;order=8;Period=Q;Days=WEEKDAYS",usedf=True);

In [21]:
data

(0,
             PRT_STOCKVALUE PRT_TOPSTOCKWINDCODE
 2020-12-31    1.790837e+10            000895.SZ
 2021-03-31    2.374960e+10            000739.SZ
 2021-06-30    2.745870e+10            688099.SH
 2021-09-30    2.667316e+10            603707.SH
 2021-12-31    3.136809e+10            600754.SH
 2022-03-31    2.549094e+10            600754.SH
 2022-06-30    2.683657e+10            600438.SH
 2022-09-30    2.331552e+10            300454.SZ
 2022-12-05             NaN                 None)

In [22]:
data = w.wsd("163406.OF", "prt_stockvalue,prt_topstockwindcode", "2020-11-01", "2022-12-05", "unit=1;order=9;Period=Q;Days=WEEKDAYS",usedf=True);

In [23]:
data

(0,
             PRT_STOCKVALUE PRT_TOPSTOCKWINDCODE
 2020-12-31    1.790837e+10            688099.SH
 2021-03-31    2.374960e+10            603707.SH
 2021-06-30    2.745870e+10            000739.SZ
 2021-09-30    2.667316e+10            688099.SH
 2021-12-31    3.136809e+10            002415.SZ
 2022-03-31    2.549094e+10            002555.SZ
 2022-06-30    2.683657e+10            600873.SH
 2022-09-30    2.331552e+10            603707.SH
 2022-12-05             NaN                 None)

In [24]:
data = w.wsd("163406.OF", "prt_stockvalue,prt_topstockwindcode", "2020-11-01", "2022-12-05", "unit=1;order=10;Period=Q;Days=WEEKDAYS",usedf=True);

In [25]:
data

(0,
             PRT_STOCKVALUE PRT_TOPSTOCKWINDCODE
 2020-12-31    1.790837e+10            601012.SH
 2021-03-31    2.374960e+10            300413.SZ
 2021-06-30    2.745870e+10            603707.SH
 2021-09-30    2.667316e+10            600754.SH
 2021-12-31    3.136809e+10            000739.SZ
 2022-03-31    2.549094e+10            600873.SH
 2022-06-30    2.683657e+10            603816.SH
 2022-09-30    2.331552e+10            600309.SH
 2022-12-05             NaN                 None)

In [35]:
for i in range(10):
    error,data = w.wsd("163406.OF", "prt_stockvalue,prt_topstockwindcode,prt_topstockname", "2022-09-30", "2022-09-30", "unit=1;order={};Period=Q;Days=WEEKDAYS".format(i),usedf=True);
    print(data)

           PRT_STOCKVALUE  PRT_TOPSTOCKWINDCODE  PRT_TOPSTOCKNAME
163406.OF    2.331552e+10                   NaN               NaN
           PRT_STOCKVALUE PRT_TOPSTOCKWINDCODE PRT_TOPSTOCKNAME
163406.OF    2.331552e+10            600690.SH             海尔智家
           PRT_STOCKVALUE PRT_TOPSTOCKWINDCODE PRT_TOPSTOCKNAME
163406.OF    2.331552e+10            002120.SZ             韵达股份
           PRT_STOCKVALUE PRT_TOPSTOCKWINDCODE PRT_TOPSTOCKNAME
163406.OF    2.331552e+10            600703.SH             三安光电
           PRT_STOCKVALUE PRT_TOPSTOCKWINDCODE PRT_TOPSTOCKNAME
163406.OF    2.331552e+10            002475.SZ             立讯精密
           PRT_STOCKVALUE PRT_TOPSTOCKWINDCODE PRT_TOPSTOCKNAME
163406.OF    2.331552e+10            600873.SH             梅花生物
           PRT_STOCKVALUE PRT_TOPSTOCKWINDCODE PRT_TOPSTOCKNAME
163406.OF    2.331552e+10            300413.SZ             芒果超媒
           PRT_STOCKVALUE PRT_TOPSTOCKWINDCODE PRT_TOPSTOCKNAME
163406.OF    2.331552e+10            002938.SZ             鹏鼎控股
           PRT_STOCKVALUE PRT_TOPSTOCKWINDCODE PRT_TOPSTOCKNAME
163406.OF    2.331552e+10            300454.SZ              深信服
           PRT_STOCKVALUE PRT_TOPSTOCKWINDCODE PRT_TOPSTOCKNAME
163406.OF    2.331552e+10            603707.SH             健友股份

In [52]:
import pandas as pd
time ="2022-06-30"
data=[]
for i in range(10):
    error,data_i = w.wsd("163406.OF", "prt_heavilyheldstocktoasset,prt_topstockname", time,time , "unit=1;order={};Period=Q;Days=WEEKDAYS".format(i),usedf=True);
    data.append(data_i)

pd.concat(data)

           PRT_HEAVILYHELDSTOCKTOASSET PRT_TOPSTOCKNAME
163406.OF                          NaN             None
163406.OF                     7.149898             海尔智家
163406.OF                     4.413925             三安光电
163406.OF                     3.984934             闻泰科技
163406.OF                     3.935614             芒果超媒
163406.OF                     3.423954             锦江酒店
163406.OF                     3.346352             晶晨股份
163406.OF                     3.337423             健友股份
163406.OF                     3.221104             通威股份
163406.OF                     3.029046             梅花生物

In [54]:
import pandas as pd
time ="2022-03-31"
data=[]
for i in range(10):
    error,data_i = w.wsd("163406.OF", "prt_heavilyheldstocktoasset,prt_topstockname", time,time , "unit=1;order={};Period=Q;Days=WEEKDAYS".format(i),usedf=True);
    data.append(data_i)

pd.concat(data)

           PRT_HEAVILYHELDSTOCKTOASSET PRT_TOPSTOCKNAME
163406.OF                          NaN             None
163406.OF                     7.301649             海尔智家
163406.OF                     4.373791             三安光电
163406.OF                     3.893482             晶晨股份
163406.OF                     3.886447             普洛药业
163406.OF                     3.878381             芒果超媒
163406.OF                     3.779922             闻泰科技
163406.OF                     3.764913             健友股份
163406.OF                     3.360272             锦江酒店
163406.OF                     2.841169             三七互娱

In [49]:
pd.concat(data)

           PRT_HEAVILYHELDSTOCKTOASSET PRT_TOPSTOCKNAME
163406.OF                          NaN             None
163406.OF                     7.149898             海尔智家
163406.OF                     4.413925             三安光电
163406.OF                     3.984934             闻泰科技
163406.OF                     3.935614             芒果超媒
163406.OF                     3.423954             锦江酒店
163406.OF                     3.346352             晶晨股份
163406.OF                     3.337423             健友股份
163406.OF                     3.221104             通威股份
163406.OF                     3.029046             梅花生物

In [ ]:
for i in range(10):
    error,data = w.wsd("163406.OF", "prt_stockvalue,prt_topstockwindcode,prt_topstockname", "2022-09-30", "2022-09-30", "unit=1;order={};Period=Q;Days=WEEKDAYS".format(i),usedf=True);
    print(data)

In [55]:
import pandas as pd
time ="2022-09-30"
data=[]
for i in range(10):
    error,data_i = w.wsd("163406.OF", "prt_heavilyheldstocktoasset,prt_topstockname", time,time , "unit=1;order={};Period=Q;Days=WEEKDAYS".format(i),usedf=True);
    data.append(data_i)

pd.concat(data)

           PRT_HEAVILYHELDSTOCKTOASSET PRT_TOPSTOCKNAME
163406.OF                          NaN             None
163406.OF                     7.538236             海尔智家
163406.OF                     3.948726             韵达股份
163406.OF                     3.869451             三安光电
163406.OF                     3.809032             立讯精密
163406.OF                     3.545500             梅花生物
163406.OF                     3.473605             芒果超媒
163406.OF                     3.346825             鹏鼎控股
163406.OF                     3.333355              深信服
163406.OF                     3.218296             健友股份

In [56]:
import pandas as pd
time ="2021-12-31"
data=[]
for i in range(10):
    error,data_i = w.wsd("163406.OF", "prt_heavilyheldstocktoasset,prt_topstockname", time,time , "unit=1;order={};Period=Q;Days=WEEKDAYS".format(i),usedf=True);
    data.append(data_i)

pd.concat(data)

           PRT_HEAVILYHELDSTOCKTOASSET PRT_TOPSTOCKNAME
163406.OF                          NaN             None
163406.OF                     6.303932             海尔智家
163406.OF                     4.665681             三安光电
163406.OF                     4.519844             万华化学
163406.OF                     3.763782             芒果超媒
163406.OF                     3.700005             闻泰科技
163406.OF                     3.437411             晶晨股份
163406.OF                     3.424828             健友股份
163406.OF                     3.374644             锦江酒店
163406.OF                     3.075910             海康威视

In [57]:
import pandas as pd
time ="2021-09-30"
data=[]
for i in range(10):
    error,data_i = w.wsd("163406.OF", "prt_heavilyheldstocktoasset,prt_topstockname", time,time , "unit=1;order={};Period=Q;Days=WEEKDAYS".format(i),usedf=True);
    data.append(data_i)

pd.concat(data)

           PRT_HEAVILYHELDSTOCKTOASSET PRT_TOPSTOCKNAME
163406.OF                          NaN             None
163406.OF                     8.279344             海尔智家
163406.OF                     5.825868             万华化学
163406.OF                     4.743846             海康威视
163406.OF                     4.070939             三安光电
163406.OF                     3.959624             兴业银行
163406.OF                     3.716921             芒果超媒
163406.OF                     3.712812             普洛药业
163406.OF                     3.644122             健友股份
163406.OF                     3.336436             晶晨股份

In [58]:
import pandas as pd
time ="2021-06-30"
data=[]
for i in range(10):
    error,data_i = w.wsd("163406.OF", "prt_heavilyheldstocktoasset,prt_topstockname", time,time , "unit=1;order={};Period=Q;Days=WEEKDAYS".format(i),usedf=True);
    data.append(data_i)

pd.concat(data)

           PRT_HEAVILYHELDSTOCKTOASSET PRT_TOPSTOCKNAME
163406.OF                          NaN             None
163406.OF                     8.259206             海尔智家
163406.OF                     6.082579             平安银行
163406.OF                     5.822399             海康威视
163406.OF                     4.294683             兴业银行
163406.OF                     3.840057             万华化学
163406.OF                     3.361701             锦江酒店
163406.OF                     3.185169             芒果超媒
163406.OF                     3.086441             晶晨股份
163406.OF                     2.927344             普洛药业

In [59]:
import pandas as pd
time ="2021-03-31"
data=[]
for i in range(10):
    error,data_i = w.wsd("163406.OF", "prt_heavilyheldstocktoasset,prt_topstockname", time,time , "unit=1;order={};Period=Q;Days=WEEKDAYS".format(i),usedf=True);
    data.append(data_i)

pd.concat(data)

           PRT_HEAVILYHELDSTOCKTOASSET PRT_TOPSTOCKNAME
163406.OF                          NaN             None
163406.OF                     7.180096             海尔智家
163406.OF                     5.781927             兴业银行
163406.OF                     5.571840             平安银行
163406.OF                     4.699739             中国平安
163406.OF                     3.801951             海康威视
163406.OF                     3.695813             三一重工
163406.OF                     3.428071             锦江酒店
163406.OF                     3.125156             普洛药业
163406.OF                     3.042970             健友股份

In [61]:
import pandas as pd
time ="2019-12-31"
data=[]
for i in range(10):
    error,data_i = w.wsd("163406.OF", "prt_heavilyheldstocktoasset,prt_topstockname", time,time , "unit=1;order={};Period=Q;Days=WEEKDAYS".format(i),usedf=True);
    data.append(data_i)

pd.concat(data)

           PRT_HEAVILYHELDSTOCKTOASSET PRT_TOPSTOCKNAME
163406.OF                          NaN             None
163406.OF                     9.767601             隆基绿能
163406.OF                     5.933855             中国平安
163406.OF                     5.064290             万华化学
163406.OF                     3.971071             健友股份
163406.OF                     3.873993             芒果超媒
163406.OF                     3.457474             大族激光
163406.OF                     2.933590             三一重工
163406.OF                     2.721962             领益智造
163406.OF                     2.641434             美年健康

In [62]:
import pandas as pd
time ="2019-09-30"
data=[]
for i in range(10):
    error,data_i = w.wsd("163406.OF", "prt_heavilyheldstocktoasset,prt_topstockname", time,time , "unit=1;order={};Period=Q;Days=WEEKDAYS".format(i),usedf=True);
    data.append(data_i)

pd.concat(data)

           PRT_HEAVILYHELDSTOCKTOASSET PRT_TOPSTOCKNAME
163406.OF                          NaN             None
163406.OF                     9.415699             隆基绿能
163406.OF                     6.985157             中国平安
163406.OF                     6.173412             永辉超市
163406.OF                     4.609618             健友股份
163406.OF                     4.119939             万华化学
163406.OF                     3.427634             三一重工
163406.OF                     3.040393             通威股份
163406.OF                     2.995053             大族激光
163406.OF                     2.880749             领益智造

In [63]:
import pandas as pd
time ="2020-03-31"
data=[]
for i in range(10):
    error,data_i = w.wsd("163406.OF", "prt_heavilyheldstocktoasset,prt_topstockname", time,time , "unit=1;order={};Period=Q;Days=WEEKDAYS".format(i),usedf=True);
    data.append(data_i)

pd.concat(data)

           PRT_HEAVILYHELDSTOCKTOASSET PRT_TOPSTOCKNAME
163406.OF                          NaN             None
163406.OF                    10.196166             隆基绿能
163406.OF                     4.549055             保利发展
163406.OF                     4.377673              万科A
163406.OF                     3.988181             中国平安
163406.OF                     3.871348             健友股份
163406.OF                     3.698287             万华化学
163406.OF                     3.490292             芒果超媒
163406.OF                     3.211340              凯莱英
163406.OF                     2.980606             普洛药业

In [64]:
import pandas as pd
time ="2020-06-30"
data=[]
for i in range(10):
    error,data_i = w.wsd("163406.OF", "prt_heavilyheldstocktoasset,prt_topstockname", time,time , "unit=1;order={};Period=Q;Days=WEEKDAYS".format(i),usedf=True);
    data.append(data_i)

pd.concat(data)

           PRT_HEAVILYHELDSTOCKTOASSET PRT_TOPSTOCKNAME
163406.OF                          NaN             None
163406.OF                     9.002291             隆基绿能
163406.OF                     4.693150             芒果超媒
163406.OF                     4.654541             中国平安
163406.OF                     4.193188             万华化学
163406.OF                     3.343490             三一重工
163406.OF                     3.263282             健友股份
163406.OF                     3.170102             汇川技术
163406.OF                     3.085258             仙琚制药
163406.OF                     2.897017             华海药业

In [65]:
import pandas as pd
time ="2020-09-30"
data=[]
for i in range(10):
    error,data_i = w.wsd("163406.OF", "prt_heavilyheldstocktoasset,prt_topstockname", time,time , "unit=1;order={};Period=Q;Days=WEEKDAYS".format(i),usedf=True);
    data.append(data_i)

pd.concat(data)

           PRT_HEAVILYHELDSTOCKTOASSET PRT_TOPSTOCKNAME
163406.OF                          NaN             None
163406.OF                     7.065168             隆基绿能
163406.OF                     4.657139             万华化学
163406.OF                     4.486152              比亚迪
163406.OF                     4.130795             中国平安
163406.OF                     3.550732             领益智造
163406.OF                     3.483956             美的集团
163406.OF                     3.461573             海尔智家
163406.OF                     3.174420             三一重工
163406.OF                     3.133358             芒果超媒

In [66]:
import pandas as pd
time ="2020-12-31"
data=[]
for i in range(10):
    error,data_i = w.wsd("163406.OF", "prt_heavilyheldstocktoasset,prt_topstockname", time,time , "unit=1;order={};Period=Q;Days=WEEKDAYS".format(i),usedf=True);
    data.append(data_i)

pd.concat(data)

           PRT_HEAVILYHELDSTOCKTOASSET PRT_TOPSTOCKNAME
163406.OF                          NaN             None
163406.OF                     6.647837             中国平安
163406.OF                     6.347456             海尔智家
163406.OF                     5.447405             三一重工
163406.OF                     3.872313             美的集团
163406.OF                     3.483485             万华化学
163406.OF                     3.349777              比亚迪
163406.OF                     3.278745             芒果超媒
163406.OF                     3.100093             双汇发展
163406.OF                     2.834387             晶晨股份